### ISSUE TITLE
Convert getting-started demos to English

### ISSUE THREAD

**Issue by weakish** [leancloud/docs-en#245]
- js
    * [x] express leancloud/node-js-getting-started#39
    * [x] koa leancloud/koa-getting-started#4
- python
    * [x] flask leancloud/python-getting-started#32 leancloud/python-getting-started#38
    * [x] django leancloud/django-getting-started#8 leancloud/django-getting-started#9
- php
    * [x] slim leancloud/slim-getting-started#5
    * laravel 暂不英化 （似乎处于濒临废弃状态，最近的 commit  在 2016 年 1 月，`lean init` 也并不包含这个项目）
- java
    * [x] servlet leancloud/java-war-getting-started#10
    * [x] spring-boot leancloud/spring-boot-getting-started#3
- c# 暂不英化（目前 docs-en 并没有 C# 的云引擎开发指南）
